name          'gdsoperations-gor'
version       '0.2.0'
source        'https://github.com/alphagov/puppet-gor'
author        'Government Digital Service'
license       'MIT'
summary       'Puppet module for Gor'
description   'Puppet module for Gor'
project_page  'https://github.com/alphagov/puppet-gor'

dependency 'puppetlabs/stdlib', '>= 3.0.0'
